export const ERROR_CODES = {
  BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
  BOOK_ALREADY_EXISTS: "BOOK_ALREADY_EXISTS",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  INTERNAL_ERROR: "INTERNAL_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
